In [2]:
import numpy as np

In [3]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [6]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
np.empty(3)

array([0., 0., 0.])

In [8]:
np.random.seed(0)

In [9]:
np.random.randint(5,size=(1,5))

array([[4, 0, 3, 3, 3]])

In [10]:
x=np.arange(5)

In [11]:


x

array([0, 1, 2, 3, 4])

In [12]:
np.add.reduce(x)

10

In [13]:
np.multiply.accumulate(x)


array([0, 0, 0, 0, 0], dtype=int32)

In [23]:
x = np.arange(1,10).reshape((3,3))

In [24]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
x[np.newaxis,:]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [27]:
bins = np.linspace(-5,5,20)

In [28]:
bins

array([-5.        , -4.47368421, -3.94736842, -3.42105263, -2.89473684,
       -2.36842105, -1.84210526, -1.31578947, -0.78947368, -0.26315789,
        0.26315789,  0.78947368,  1.31578947,  1.84210526,  2.36842105,
        2.89473684,  3.42105263,  3.94736842,  4.47368421,  5.        ])

In [29]:
count = np.zeros_like(bins)

In [30]:
count

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])